import 'package:meta/meta.dart';
import 'package:universal_io/io.dart';

import 'parser.dart';
import 'version.dart';

// Conditional imports for web support
import 'dotenv_io.dart' if (dart.library.html) 'dotenv_web.dart' as platform;
import 'stderr_io.dart' if (dart.library.html) 'stderr_web.dart' as stderr_impl;
import 'platform_detection_io.dart' if (dart.library.html) 'platform_detection_web.dart' as platform_detection;

/// Loads key-value pairs from a file into a [Map<String, String>].
///
/// The parser will attempt to handle simple variable substitution,
/// respect single- vs. double-quotes, and ignore `#comments` or the `export` keyword.
/// Loads environment variables from a `.env` file.
///
/// ## usage
///
/// Call [DotEnv.load] to parse the file(s).
/// Read variables from the underlying [Map] using the `[]` operator.
///
///     import 'package:dotenv/dotenv.dart';
///
///     void main() {
///       var env = DotEnv(includePlatformEnvironment: true)
///         ..load('path/to/my/.env');
///       var foo = env['foo'];
///       var homeDir = env['HOME'];
///       // ...
///     }
///
/// Verify required variables are present:
///
///     const _requiredEnvVars = ['host', 'port'];
///     bool get hasEnv => env.isEveryDefined(_requiredEnvVars);

/// Package version (from pubspec.yaml, generated by tool/generate_version.dart)
const String _packageVersion = packageVersion;

class DotEnv {
  /// If true, the underlying map will contain the entries of [Platform.environment],
  /// even after calling [clear].
  /// Otherwise, it will be empty until populated by [load].
  final bool includePlatformEnvironment;

  /// If true, suppress "file not found" messages on [stderr] during [load].
  final bool quiet;

  final _map = <String, String>{};

  DotEnv({this.includePlatformEnvironment = false, this.quiet = false}) {
    if (includePlatformEnvironment) _addPlatformEnvironment();
  }

  /// Provides access to the underlying [Map].
  ///
  /// Prefer using [operator[]] to read values.
  @visibleForTesting
  Map<String, String> get map => _map;

  /// Reads the value for [key] from the underlying map.
  ///
  /// Returns `null` if [key] is absent.  See [isDefined].
  String? operator [](String key) => _map[key];

  /// Calls [Map.addAll] on the underlying map.
  void addAll(Map<String, String> other) => _map.addAll(other);

  /// Calls [Map.clear] on the underlying map.
  ///
  /// If [includePlatformEnvironment] is true, the entries of [Platform.environment] will be reinserted.
  void clear() {
    _map.clear();
    if (includePlatformEnvironment) _addPlatformEnvironment();
  }

  /// Equivalent to [operator []] when the underlying map contains [key],
  /// and the value is non-empty.  See [isDefined].
  ///
  /// Otherwise, calls [orElse] and returns the value.
  String getOrElse(String key, String Function() orElse) => isDefined(key) ? _map[key]! : orElse();

  /// True if [key] has a nonempty value in the underlying map.
  ///
  /// Differs from [Map.containsKey] by excluding empty values.
  bool isDefined(String key) => _map[key]?.isNotEmpty ?? false;

  /// True if all supplied [vars] have nonempty value; false otherwise.
  ///
  /// See [isDefined].
  bool isEveryDefined(Iterable<String> vars) => vars.every(isDefined);

  /// Parses environment variables from each path in [filenames], and adds them
  /// to the underlying [Map].
  ///
  /// Automatically detects the platform (web or non-web) and loads files accordingly.
  /// On web, files are loaded via HTTP. On other platforms, files are loaded from the file system.
  ///
  /// Logs to [stderr] if any file does not exist; see [quiet].
  void load([
    Iterable<String> filenames = const ['.env'],
    Parser psr = const Parser(),
  ]) {
    if (!quiet) {
      stderr_impl.safeStderrWriteln('[dotenv] ========================================');
      stderr_impl.safeStderrWriteln('[dotenv] Package version: $_packageVersion');
      stderr_impl.safeStderrWriteln('[dotenv] DEBUG: ========================================');
      stderr_impl.safeStderrWriteln('[dotenv] DEBUG: Starting load operation');
      stderr_impl.safeStderrWriteln('[dotenv] DEBUG: Platform: ${platform_detection.getPlatformName()}');
      stderr_impl
          .safeStderrWriteln('[dotenv] DEBUG: Platform environment available: ${Platform.environment.isNotEmpty}');
      stderr_impl
          .safeStderrWriteln('[dotenv] DEBUG: dart.library.html available: ${platform_detection.isWebPlatform()}');
      stderr_impl.safeStderrWriteln('[dotenv] DEBUG: ========================================');
    }

    for (var filename in filenames) {
      if (!quiet) {
        stderr_impl.safeStderrWriteln('[dotenv] DEBUG: Attempting to load file: $filename');
      }
      var lines = platform.loadFile(filename, quiet);
      if (!quiet) {
        stderr_impl.safeStderrWriteln('[dotenv] DEBUG: Loaded ${lines.length} lines from $filename');
      }
      _map.addAll(psr.parse(lines));
    }

    if (!quiet) {
      stderr_impl.safeStderrWriteln('[dotenv] DEBUG: Load complete. Total variables: ${_map.length}');
    }
  }

  void _addPlatformEnvironment() => _map.addAll(Platform.environment);
}
